'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class csp_details

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tblHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblHeading As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''admin_link control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents admin_link As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''RadSkinManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSkinManager1 As Global.Telerik.Web.UI.RadSkinManager

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''updNotify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updNotify As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''continueSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents continueSession As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''lblStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSchool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSchool As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeacher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeacher As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMats As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbtnPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnPrev As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbtnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnNext As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''sqlCspHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlCspHeader As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlCspGoals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlCspGoals As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlCspGrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlCspGrades As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlCspComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlCspComments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''odsCspInitDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCspInitDates As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsGCCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsGCCategories As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''hdnSchoolId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSchoolId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''iep_data_uuid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iep_data_uuid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''usr_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usr_login As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rspCspDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rspCspDetails As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''rpMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpMain As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''mainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''rgCspGoals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgCspGoals As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''GridDropDownListColumnEditor4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDropDownListColumnEditor4 As Global.Telerik.Web.UI.GridDropDownListColumnEditor

    '''<summary>
    '''GridDropDownListColumnEditor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDropDownListColumnEditor1 As Global.Telerik.Web.UI.GridDropDownListColumnEditor

    '''<summary>
    '''GridDropDownListColumnEditor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDropDownListColumnEditor2 As Global.Telerik.Web.UI.GridDropDownListColumnEditor

    '''<summary>
    '''GridDropDownListColumnEditor3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDropDownListColumnEditor3 As Global.Telerik.Web.UI.GridDropDownListColumnEditor

    '''<summary>
    '''reComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reComments As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''reFNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reFNotes As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''reJNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reJNotes As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''reClipboardTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reClipboardTransfer As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''DialogWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DialogWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''ctxMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctxMenu As Global.Telerik.Web.UI.RadContextMenu

    '''<summary>
    '''RadSplitBar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitBar2 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''EndPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rslToolbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rslToolbox As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''rslpClipboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rslpClipboard As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''lbClipboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbClipboard As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''ctxClipboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctxClipboard As Global.Telerik.Web.UI.RadContextMenu

    '''<summary>
    '''rslpGoalCatalog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rslpGoalCatalog As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmbGoalCatalog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbGoalCatalog As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lbGoalCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbGoalCat As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''rslpRatings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rslpRatings As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''rgRatings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgRatings As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''reTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reTransfer As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''rgComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgComments As Global.Telerik.Web.UI.RadGrid
End Class
