'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class csp_header

    '''<summary>
    '''sqlTeachers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlTeachers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlStudents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlStudents As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlSchools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlSchools As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlSubjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlSubjects As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlAllTeachers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlAllTeachers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''usr_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usr_login As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmbSchool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSchool As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ddStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddStudent As Global.Telerik.Web.UI.RadDropDownTree

    '''<summary>
    '''cmbAllTeachers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAllTeachers As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbTeacher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTeacher As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''btnAddTeacher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTeacher As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''lbTeachers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTeachers As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''ddSubjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSubjects As Global.Telerik.Web.UI.RadDropDownTree

    '''<summary>
    '''txtSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbSubject_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubject_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubject As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMaterials As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaterials As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbYear As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsert As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.Telerik.Web.UI.RadButton
End Class
