//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eiepEntities : DbContext
    {
        public eiepEntities()
            : base("name=eiepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gc_categories> gc_categories { get; set; }
        public virtual DbSet<gc_data> gc_data { get; set; }
        public virtual DbSet<gc_goals> gc_goals { get; set; }
        public virtual DbSet<gc_goals_bak> gc_goals_bak { get; set; }
        public virtual DbSet<gc_goals_old> gc_goals_old { get; set; }
        public virtual DbSet<gc_subjects> gc_subjects { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<iep> ieps { get; set; }
        public virtual DbSet<iep_20141006> iep_20141006 { get; set; }
        public virtual DbSet<iep_bak> iep_bak { get; set; }
        public virtual DbSet<iep_data> iep_data { get; set; }
        public virtual DbSet<iep_data_20150218> iep_data_20150218 { get; set; }
        public virtual DbSet<iep_data_bak> iep_data_bak { get; set; }
        public virtual DbSet<iep_data_undo> iep_data_undo { get; set; }
        public virtual DbSet<pdf_temp> pdf_temp { get; set; }
        public virtual DbSet<pdf_temp_06172016> pdf_temp_06172016 { get; set; }
        public virtual DbSet<pdf_temp_20150603> pdf_temp_20150603 { get; set; }
        public virtual DbSet<placement> placements { get; set; }
        public virtual DbSet<schedule_course_students> schedule_course_students { get; set; }
        public virtual DbSet<schedule_courses> schedule_courses { get; set; }
        public virtual DbSet<schedule_session_exceptions> schedule_session_exceptions { get; set; }
        public virtual DbSet<schedule_sessions> schedule_sessions { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<service_providers> service_providers { get; set; }
        public virtual DbSet<service_providers_bak> service_providers_bak { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<services_bak> services_bak { get; set; }
        public virtual DbSet<services_bak_20141103> services_bak_20141103 { get; set; }
        public virtual DbSet<services_bak_20150617> services_bak_20150617 { get; set; }
        public virtual DbSet<services_students> services_students { get; set; }
        public virtual DbSet<services_tmp> services_tmp { get; set; }
        public virtual DbSet<student_accommodations> student_accommodations { get; set; }
        public virtual DbSet<student_inclusions> student_inclusions { get; set; }
        public virtual DbSet<student_inclusions_20150617> student_inclusions_20150617 { get; set; }
        public virtual DbSet<student_inclusions_bak> student_inclusions_bak { get; set; }
        public virtual DbSet<student_services> student_services { get; set; }
        public virtual DbSet<student_services_bak> student_services_bak { get; set; }
        public virtual DbSet<student_services_bak_0505> student_services_bak_0505 { get; set; }
        public virtual DbSet<student_tmp> student_tmp { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<students_20141005> students_20141005 { get; set; }
        public virtual DbSet<students_20150917> students_20150917 { get; set; }
        public virtual DbSet<students_20151013> students_20151013 { get; set; }
        public virtual DbSet<students_20161004> students_20161004 { get; set; }
        public virtual DbSet<students_bak> students_bak { get; set; }
        public virtual DbSet<students_bak_20140715> students_bak_20140715 { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<subjects_20151113> subjects_20151113 { get; set; }
        public virtual DbSet<tmp_log> tmp_log { get; set; }
        public virtual DbSet<usr> usrs { get; set; }
    }
}
