//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_data
    {
        public System.Guid gc_data_uuid { get; set; }
        public System.Guid gc_subject_uuid { get; set; }
        public short gc_data_sequence { get; set; }
        public Nullable<System.Guid> gc_data_parent_uuid { get; set; }
        public string gc_data_text { get; set; }
        public Nullable<byte> gc_sub_data_sequence { get; set; }
    }
}
