//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_goals
    {
        public System.Guid gc_goal_uuid { get; set; }
        public System.Guid gc_subject_uuid { get; set; }
        public Nullable<System.Guid> gc_parent_uuid { get; set; }
        public byte gc_goal_sequence { get; set; }
        public Nullable<byte> gc_goal_sub_sequence { get; set; }
        public string gc_goal_text { get; set; }
    }
}
