//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_subjects
    {
        public System.Guid gc_subject_uuid { get; set; }
        public Nullable<System.Guid> gc_category_uuid { get; set; }
        public string gc_subject_name { get; set; }
        public Nullable<byte> gc_subject_order { get; set; }
    }
}
