//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public byte grade_id { get; set; }
        public byte school_id { get; set; }
        public string grade_text { get; set; }
        public string grade_desc { get; set; }
    
        public virtual school school { get; set; }
    }
}
