//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class iep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iep()
        {
            this.iep_data = new HashSet<iep_data>();
            this.iep_data_20150218 = new HashSet<iep_data_20150218>();
        }
    
        public System.Guid iep_uuid { get; set; }
        public byte school_id { get; set; }
        public string iep_subject { get; set; }
        public System.Guid teacher_uuid { get; set; }
        public System.Guid student_uuid { get; set; }
        public string iep_materials { get; set; }
        public string iep_year { get; set; }
        public string iep_comments { get; set; }
        public string iep_feb_notes { get; set; }
        public string iep_june_notes { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.Guid> teacher_2_uuid { get; set; }
        public Nullable<System.Guid> teacher_3_uuid { get; set; }
        public Nullable<System.Guid> teacher_4_uuid { get; set; }
        public Nullable<System.Guid> teacher_5_uuid { get; set; }
        public string locked_by { get; set; }
        public Nullable<System.Guid> locked_by_uuid { get; set; }
        public Nullable<System.DateTime> locked_by_date { get; set; }
        public Nullable<System.Guid> iep_subject_uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iep_data> iep_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iep_data_20150218> iep_data_20150218 { get; set; }
        public virtual school school { get; set; }
        public virtual student student { get; set; }
        public virtual usr usr { get; set; }
    }
}
