//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class iep_data
    {
        public System.Guid iep_data_uuid { get; set; }
        public System.Guid iep_uuid { get; set; }
        public byte iep_data_sequence { get; set; }
        public Nullable<System.Guid> iep_data_parent_uuid { get; set; }
        public string iep_data_text { get; set; }
        public string iep_date_initiated { get; set; }
        public Nullable<byte> iep_data_grade_1_id { get; set; }
        public Nullable<byte> iep_data_grade_2_id { get; set; }
        public Nullable<byte> iep_data_grade_3_id { get; set; }
        public Nullable<byte> iep_sub_data_sequence { get; set; }
    
        public virtual iep iep { get; set; }
    }
}
