//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdf_temp
    {
        public System.Guid pdf_uuid { get; set; }
        public string pdf_fo { get; set; }
    }
}
