//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_courses
    {
        public System.Guid course_uuid { get; set; }
        public Nullable<byte> school_id { get; set; }
        public string course_name { get; set; }
        public string course_color { get; set; }
        public Nullable<System.Guid> teacher_uuid { get; set; }
    }
}
