//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_tmp
    {
        public System.Guid services_uuid { get; set; }
        public System.Guid provider_uuid { get; set; }
        public string services_name { get; set; }
        public string service_model { get; set; }
        public string student_list { get; set; }
        public string session_length { get; set; }
        public string weekly_sessions { get; set; }
        public string session_start_date { get; set; }
    }
}
