//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_accommodations
    {
        public System.Guid accommodations_uuid { get; set; }
        public System.Guid student_uuid { get; set; }
        public string accommodation_details { get; set; }
    }
}
