//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_services_bak
    {
        public System.Guid services_uuid { get; set; }
        public System.Guid student_uuid { get; set; }
        public string services_name { get; set; }
        public string provider_name { get; set; }
        public string service_model { get; set; }
        public byte num_students { get; set; }
        public string session_length { get; set; }
        public string weekly_sessions { get; set; }
        public string session_start_date { get; set; }
        public string session_end_date { get; set; }
        public Nullable<System.Guid> services_parent { get; set; }
    }
}
