//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_inclusions_20150617
    {
        public System.Guid inclusion_uuid { get; set; }
        public System.Guid student_uuid { get; set; }
        public string subject_name { get; set; }
        public string num_classes { get; set; }
        public string teacher_name { get; set; }
        public string session_start_date { get; set; }
        public string session_end_date { get; set; }
    }
}
