//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_bak_20140715
    {
        public System.Guid student_uuid { get; set; }
        public string student_first_name { get; set; }
        public string student_last_name { get; set; }
        public bool is_active { get; set; }
        public Nullable<byte> school_id { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string student_sex { get; set; }
        public string student_classification { get; set; }
        public string native_language { get; set; }
        public Nullable<byte> student_grade { get; set; }
        public string current_placement { get; set; }
        public string parent_primary { get; set; }
        public string parent_secondary { get; set; }
        public string home_address { get; set; }
        public string home_city { get; set; }
        public string home_state { get; set; }
        public string home_phone { get; set; }
        public string father_cell { get; set; }
        public string mother_cell { get; set; }
        public string school_year { get; set; }
        public Nullable<System.Guid> master_student_uuid { get; set; }
    }
}
