//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        public System.Guid subject_uuid { get; set; }
        public Nullable<System.Guid> subject_category { get; set; }
        public string subject_name { get; set; }
        public byte subject_order { get; set; }
    }
}
