//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinai_Console_ImportOldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usr()
        {
            this.ieps = new HashSet<iep>();
        }
    
        public System.Guid usr_uuid { get; set; }
        public string usr_login { get; set; }
        public string usr_display_name { get; set; }
        public byte role_id { get; set; }
        public System.DateTime last_login { get; set; }
        public bool is_active { get; set; }
        public string usr_title { get; set; }
        public Nullable<byte> school_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iep> ieps { get; set; }
    }
}
