//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaicsp_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoalCatalog()
        {
            this.GoalCatalogs = new HashSet<GoalCatalog>();
        }
    
        public int Id { get; set; }
        public int CreatedByUserId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string TextGoal { get; set; }
        public Nullable<int> ParentGoalCatalogId { get; set; }
        public int GC_SubjectsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalCatalog> GoalCatalogs { get; set; }
        public virtual GoalCatalog ParentGoalCatalog { get; set; }
        public virtual GC_Subjects GC_Subjects { get; set; }
    }
}
