//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaicsp_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinaicspDataModelContainer : DbContext
    {
        public SinaicspDataModelContainer()
            : base("name=SinaicspDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentClass> StudentClasses { get; set; }
        public virtual DbSet<StudentGrade> StudentGrades { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Inclusion> Inclusions { get; set; }
        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SchoolYear> SchoolYears { get; set; }
        public virtual DbSet<CSP> CSPs { get; set; }
        public virtual DbSet<TeacherCSP> TeacherCSPs { get; set; }
        public virtual DbSet<Lock> Locks { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<StudentService> StudentServices { get; set; }
        public virtual DbSet<GoalCatalog> GoalCatalogs { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<CSPGoalCatalog> CSPGoalCatalogs { get; set; }
        public virtual DbSet<GC_Category> GC_Category { get; set; }
        public virtual DbSet<GC_Subjects> GC_Subjects { get; set; }
    }
}
