//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaicsp_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Inclusions = new HashSet<Inclusion>();
            this.CSPs = new HashSet<CSP>();
            this.Locks = new HashSet<Lock>();
            this.Accommodations = new HashSet<Accommodation>();
            this.StudentServices = new HashSet<StudentService>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string PrimaryParent { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string MotherCell { get; set; }
        public int SchoolId { get; set; }
        public int StudentClassId { get; set; }
        public int StudentGradeId { get; set; }
        public string SecondaryParent { get; set; }
        public int CityId { get; set; }
        public string Phone { get; set; }
        public string FatherCell { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedByUserId { get; set; }
    
        public virtual School School { get; set; }
        public virtual StudentClass StudentClass { get; set; }
        public virtual StudentGrade StudentGrade { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inclusion> Inclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSP> CSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lock> Locks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accommodation> Accommodations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentService> StudentServices { get; set; }
    }
}
