'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admProviderServices

    '''<summary>
    '''sqlProviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlProviders As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlServices As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlSchools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlSchools As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''hdnServicesParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnServicesParent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlServices As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''cmbProviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProviders As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtNewProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewProvider As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnNewProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewProvider As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbSchools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSchools As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbStudentFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStudentFilter As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rgServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgServices As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''odsDateList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDateList As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ddSessionStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSessionStart As Global.Telerik.Web.UI.GridDropDownListColumnEditor

    '''<summary>
    '''ddSessionEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSessionEnd As Global.Telerik.Web.UI.GridDropDownListColumnEditor
End Class
